nc: 8

stream1:
  # (bs, in_ch, h, w)
  # [from, repeats, module, [out_ch, padding, stride]]
  - [-1, 1, ConvNorm, [64, 1, 1]]     # (bs, 64, h, w)
  - [-1, 5, Conv]


stream2:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [32, ]]
