nc: 8

semg-encoder:
  # (bs, in_ch, h, w)   (64, 5, 
  # [from, repeats, module, [out_ch, padding, stride]]
  - [-1, 1, ConvNorm, [64, 1, 1]]     # (bs, 64, h, w)
  - [-1, 5, Conv]


acc-encoder:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [32, ]]